name: Test ssh-agent svc
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    name: Test
    steps:
      - name: Test
        shell: powershell
        run: |
          Get-Service -Name ssh-agent | Set-Service -StartupType Manual
          Start-Service ssh-agent
          Get-Service ssh-agent
          
