name: Mamba on upgraded Conda (23.1.0) @Ubuntu20
on:
  workflow_dispatch:

jobs:
  bash-test:
    runs-on: [Ubuntu-20.04]
    name: Downgrade Conda and Mamba
    steps:
      - name: Upgrade conda, try install mamba
        shell: bash
        run: |
          echo '##### Conda info'
          conda info
          conda list
          echo '##### Upgrade to Conda 23.1.0'
          conda install conda=23.1.0 -y
          echo '##### Conda info'
          conda info
          conda list
          echo '##### Install Mamba'
          conda install --yes -c conda-forge mamba
          
