
name: Test MacOS C++ <map>
on:
  workflow_dispatch:

jobs:
  cpp-test:
    runs-on: macos-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Run Test"
        run: |
           g++ test-macos-cpp-01.cpp
           ./a.out
