name: Test Python getenv
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    name: Test
    steps:
      - shell: powershell
        run: |
          python -c "import os; print(getenv('APPDATA'))"
          python -c "import os; assert os.getenv('APPDATA') is not None"
