name: Mamba on downgraded Conda (4.12.0)
on:
  workflow_dispatch:

jobs:
  bash-test:
    runs-on: [Ubuntu-20.04]
    name: Downgrade Conda and Mamba
    steps:
      - shell: bash
        run: |
          echo '##### Current Conda info'
          conda info
          conda list
          echo '##### Downgrade to Conda 4.12.0'
          conda config --set allow_conda_downgrades true
          conda install conda=4.12.0 -y
          echo '##### Install Mamba info'
          conda install --yes -c conda-forge mamba
          echo '##### New Conda info'
          conda info
          conda list
