name: Test OPA
on:
  workflow_dispatch:

jobs:
  tf-plan:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ${{ github.workspace }}/terraform

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Terraform Install"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.4
      - name: "Setup OPA"
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.48.0
      - name: "Path Test"
        run : pwd
      - name: "Terraform Init"
        run : terraform init
      - name: "Terraform Validate"
        run : terraform validate
      - name: "Terraform Plan"
        run : terraform plan -lock=false --out tfplan.binary
      - name: "Run OPA Tests"
        run: |
          terraform show -json tfplan.binary > tfplan.json
          opa eval data.policy.mandatory_tags -d ${{ github.workspace }}/json.data -i tfplan.json -f pretty
